# Generated by Django 5.1.7 on 2025-03-15 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_documento', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=255, null=True)),
                ('nro_celular', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('tipodocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipodocumento')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tesis', models.CharField(blank=True, max_length=255, null=True)),
                ('universidad', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_plataforma', models.CharField(blank=True, max_length=25, null=True)),
                ('clave_plataforma', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registros.clientes')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
            ],
            options={
                'db_table': 'tesis',
            },
        ),
        migrations.CreateModel(
            name='Pagosclientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_tesis', models.FloatField(blank=True, null=True)),
                ('monto_cuotas', models.FloatField(blank=True, null=True)),
                ('fecha_pago_inicial', models.DateField(blank=True, null=True)),
                ('fecha_pago_final', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cuotas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cuotas')),
                ('cuotas_pagadas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cuotaspagadas')),
                ('tesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registros.tesis')),
            ],
            options={
                'db_table': 'pagosclientes',
            },
        ),
    ]
