# Generated by Django 5.1.7 on 2025-03-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallespagoclientes',
            name='monto_cuotas',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
