# Generated by Django 5.1.7 on 2025-03-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pagosclientes',
        ),
    ]
