# Generated by Django 5.1.7 on 2025-03-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pagos',
        ),
    ]
