# Generated by Django 5.1.7 on 2025-03-15 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('app_registros', '0002_delete_pagosclientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagosclientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_tesis', models.FloatField(blank=True, null=True)),
                ('monto_cuotas', models.FloatField(blank=True, null=True)),
                ('fecha_pago_inicial', models.DateField(blank=True, null=True)),
                ('fecha_pago_final', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cuotas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cuotas')),
                ('cuotas_pagadas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cuotaspagadas')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
                ('estado_pagos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estadopagos')),
                ('tesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registros.tesis')),
            ],
            options={
                'db_table': 'pagosclientes',
            },
        ),
    ]
