# Generated by Django 5.1.7 on 2025-03-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0003_pagosclientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosclientes',
            name='fecha_pago_final',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pagosclientes',
            name='fecha_pago_inicial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
