# Generated by Django 5.1.7 on 2025-03-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registros', '0004_alter_pagosclientes_fecha_pago_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosclientes',
            name='fecha_pago_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagosclientes',
            name='fecha_pago_inicial',
            field=models.DateField(blank=True, null=True),
        ),
    ]
