# Generated by Django 5.1.7 on 2025-03-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotas',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cuotaspagadas',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
