# Generated by Django 5.1.7 on 2025-03-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('app_registros', '0002_delete_pagos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formapago',
        ),
    ]
